implement BIT b,r
sambattalio/gameboy pull request #20
Opened 2020-01-28 20:25 UTC by ginglis13

pretty similar logic to `SET b,r`. Just `AND` some hex to check if a bit is zero - if so, set the `ZERO` flag.

2020-01-30 19:19 UTC, ginglis13 commented
@sambattalio do you want me to fix this as per #23 ?

2020-01-31 01:48 UTC, sambattalio commented
@ginglis13 yes please. Also, I added a new macro SET_REGISTER which might help out. It's all over if you need an example/

2020-01-31 05:46 UTC, ginglis13 commented
I'm not sure i'll use the `SET_REGISTER` macro since all that's need is to `SET_ZERO` if the check is just that the bit `b` in reg `r` is 0.

I do have a question about the HL register - I'm leaving it as a reference in `p->memory` since it looks like as you said in that issue that `(HL)` is dereferencing memory. 

Pushing those changes, lmk yo

also sorry about all the extra commits from merging lol - hopefully those can be squashed.

2020-01-31 05:55 UTC, sambattalio requested changes
Yo I think theres a few more if you dont mind grabbing them. Like ~CB 0x40ish

2020-01-31 05:55 UTC, sambattalio commented on src/proc.c
> +            if( p->memory[p->registers.h] == (p->memory[p->registers.h] & 0xFE) ){
Yo I think there are a few more you might need to grab if you don't mind

2020-01-31 05:55 UTC, sambattalio commented on src/proc.c
> +            if( p->memory[p->registers.e] == (p->memory[p->registers.e] & 0xFE) ){
another one

2020-01-31 05:55 UTC, ginglis13 commented on src/proc.c
> +            if( p->memory[p->registers.e] == (p->memory[p->registers.e] & 0xFE) ){
good call yo

2020-01-31 06:09 UTC, sambattalio commented
I’ll peep this in the morning ty ginglis

2020-01-31 16:15 UTC, sambattalio commented
think you got it nice thanks

2020-01-31 16:16 UTC, merged

2020-01-31 17:07 UTC, ginglis13 commented
@sambattalio i think later today I'm gonna add tests for this and maybe some other instructions

2020-01-31 17:17 UTC, sambattalio commented
oh that sounds good. But you might wanna wait a second to do that. I was thinking of doing test ROMs for the instruction testing instead of testing in C. thought that would be more fun. Im gonna try to get it set up today and I'll lyk it shouldn't be bad (probably should be easier than C)
@ginglis13

2020-01-31 19:18 UTC, ginglis13 commented
awesome sounds dope @sambattalio